    name: Run Python Script

    on:
      push:
        branches: [ main ] # Trigger on push to the main branch
      pull_request:
        branches: [ main ] # Trigger on pull requests to the main branch

    jobs:
      build:
        runs-on: ubuntu-latest # Specify the runner environment

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4 # Get your repository's code

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11' # Specify your desired Python version (e.g., '3.9', '3.10', '3.11')

        - name: Run Python script
          run: passwordprojectsimpler.py # Execute your Python file
