name: Run Python Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.7' # Specify your desired Python version
    - name: Install dependencies
      run: pip install -r requirements.txt # If you have a requirements.txt
    - name: Run script
      run: python passwordprojectsimpler.py
